# Generated by Django 3.2.15 on 2022-12-15 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ledgerapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ledger',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='ledger',
            name='is_deleted',
        ),
    ]
