# Generated by Django 3.2.15 on 2022-12-19 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogquestionapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questionpost',
            name='category',
        ),
        migrations.DeleteModel(
            name='QuestionCategory',
        ),
    ]
