# Generated by Django 3.2.15 on 2022-12-19 06:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=50)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('description', models.TextField()),
                ('active', models.CharField(choices=[('비료', '비료'), ('농약', '농약'), ('인력', '인력')], max_length=100)),
                ('image', models.ImageField(blank=True, upload_to='images')),
                ('level', models.CharField(choices=[('경운정지', '경운정지'), ('김매기', '김매기'), ('묘판관리', '묘판관리'), ('물주기', '물주기'), ('병해충방제', '병해충방제'), ('비닐피복및흙덮기', '비닐피복및흙덮기'), ('비닐피복및흙덮기제거', '비닐피복및흙덮기제거'), ('선별및포장', '선별및포장'), ('솎아내기', '솎아내기'), ('수정', '수정'), ('수확', '수확'), ('순지르기및눈따기', '순지르기및눈따기'), ('아주심기', '아주심기'), ('온도관리', '온도관리'), ('운반및저장', '운반및저장'), ('웃비료주기', '웃비료주기'), ('유인', '유인'), ('접목', '접목'), ('제초', '제초'), ('종자준비및소독', '종자준비및소독'), ('지주(네트)세우기', '지주(네트)세우기'), ('탈곡', '탈곡'), ('퇴비및밑비료주기', '퇴비및밑비료주기'), ('파종', '파종'), ('하우스관리', '하우스관리'), ('한때심기', '한때심기'), ('구입및판매', '구입및판매'), ('영농교육', '영농교육'), ('건조', '건조'), ('묘상준비및설치', '묘상준비및설치'), ('비닐씌우기/벗기기', '비닐씌우기/벗기기')], max_length=100)),
                ('item', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='calendarapp.item')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
