# Generated by Django 3.2.15 on 2022-12-15 23:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('calendarapp', '0002_auto_20210717_1606'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='event',
            name='active',
            field=models.CharField(choices=[('비료', '비료'), ('농약', '농약'), ('인력', '인력')], default='비료', max_length=100),
        ),
        migrations.AddField(
            model_name='event',
            name='image',
            field=models.ImageField(blank=True, upload_to='calendar/<django.db.models.fields.related.ForeignKey>/images/%Y/%m/%D'),
        ),
        migrations.AddField(
            model_name='event',
            name='level',
            field=models.CharField(choices=[('경운정지', '경운정지'), ('김매기', '김매기'), ('묘판관리', '묘판관리'), ('물주기', '물주기'), ('병해충방제', '병해충방제'), ('비닐피복및흙덮기', '비닐피복및흙덮기'), ('비닐피복및흙덮기제거', '비닐피복및흙덮기제거'), ('선별및포장', '선별및포장'), ('솎아내기', '솎아내기'), ('수정', '수정'), ('수확', '수확'), ('순지르기및눈따기', '순지르기및눈따기'), ('아주심기', '아주심기'), ('온도관리', '온도관리'), ('운반및저장', '운반및저장'), ('웃비료주기', '웃비료주기'), ('유인', '유인'), ('접목', '접목'), ('제초', '제초'), ('종자준비및소독', '종자준비및소독'), ('지주(네트)세우기', '지주(네트)세우기'), ('탈곡', '탈곡'), ('퇴비및밑비료주기', '퇴비및밑비료주기'), ('파종', '파종'), ('하우스관리', '하우스관리'), ('한때심기', '한때심기'), ('구입및판매', '구입및판매'), ('영농교육', '영농교육'), ('건조', '건조'), ('묘상준비및설치', '묘상준비및설치'), ('비닐씌우기/벗기기', '비닐씌우기/벗기기')], default='비료', max_length=100),
        ),
        migrations.AlterField(
            model_name='event',
            name='title',
            field=models.CharField(max_length=50),
        ),
        migrations.DeleteModel(
            name='EventMember',
        ),
        migrations.AddField(
            model_name='event',
            name='item',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='calendarapp.item'),
        ),
    ]
