# Generated by Django 3.2.15 on 2022-12-16 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendarapp', '0003_auto_20221215_2357'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='name',
            new_name='item',
        ),
        migrations.AlterField(
            model_name='event',
            name='active',
            field=models.CharField(choices=[('비료', '비료'), ('농약', '농약'), ('인력', '인력')], max_length=100),
        ),
        migrations.AlterField(
            model_name='event',
            name='image',
            field=models.ImageField(blank=True, upload_to='calendar/images/%Y/%m/%D'),
        ),
        migrations.AlterField(
            model_name='event',
            name='level',
            field=models.CharField(choices=[('경운정지', '경운정지'), ('김매기', '김매기'), ('묘판관리', '묘판관리'), ('물주기', '물주기'), ('병해충방제', '병해충방제'), ('비닐피복및흙덮기', '비닐피복및흙덮기'), ('비닐피복및흙덮기제거', '비닐피복및흙덮기제거'), ('선별및포장', '선별및포장'), ('솎아내기', '솎아내기'), ('수정', '수정'), ('수확', '수확'), ('순지르기및눈따기', '순지르기및눈따기'), ('아주심기', '아주심기'), ('온도관리', '온도관리'), ('운반및저장', '운반및저장'), ('웃비료주기', '웃비료주기'), ('유인', '유인'), ('접목', '접목'), ('제초', '제초'), ('종자준비및소독', '종자준비및소독'), ('지주(네트)세우기', '지주(네트)세우기'), ('탈곡', '탈곡'), ('퇴비및밑비료주기', '퇴비및밑비료주기'), ('파종', '파종'), ('하우스관리', '하우스관리'), ('한때심기', '한때심기'), ('구입및판매', '구입및판매'), ('영농교육', '영농교육'), ('건조', '건조'), ('묘상준비및설치', '묘상준비및설치'), ('비닐씌우기/벗기기', '비닐씌우기/벗기기')], max_length=100),
        ),
    ]
