# Generated by Django 3.2.15 on 2022-12-06 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Information',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stnId', models.IntegerField()),
                ('stnNm', models.CharField(max_length=20)),
                ('date', models.CharField(max_length=50)),
                ('tavg', models.CharField(max_length=50)),
                ('thum', models.CharField(max_length=50)),
                ('rainfall', models.CharField(max_length=50)),
                ('insolation', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'weather',
            },
        ),
    ]
